nome = input('Digite o Nome:').strip()
print(nome)
print('Olá, {}'.format(nome.upper()))
print('Olá, {}'.format(nome.lower()))
print('{} letras'.format(len(nome)- nome.count(' ')))
#print('{} letras no primeiro nome.'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome {} tem  {} letras'.format(separa[0], len(separa[0])))
print(separa)