print('==='*10)
print(' '*5, 'LISTA DE PREÇOS')
print('==='*10)
lista = ('Pão', 3.50 , 'Mortadela', 5.00, 'Manteiga', 3.00, 'Queijo', 4.00)
print(f'{lista[0]}', end='')
print('__'*5, end='')
print(f'______R${lista[1]}')
print(f'{lista[2]}', end='')
print('__'*5, end='')
print(f'R${lista[3]}')
print(f'{lista[4]}', end='')
print('__'*5, end='')
print(f'_R${lista[5]}')
print(f'{lista[6]}', end='')
print('__'*5, end='')
print(f'___R${lista[7]}')
print('++'*15)
